http {

    server {
        client_max_body_size    1;
        listen                  127.0.0.1:8080;
        server_name             instanceA;
        
        root    ./www;
        index   index.html;

        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location / {
            index root.html;
            methods GET POST;
            autoindex off;
        }


        location /html1 {
            index index.html;
            methods GET POST;
            autoindex off;
        }
    }

    server {
        client_max_body_size    100;
        listen                  192.128.15.8:8081;
        server_name             instanceB;
        
        root    ./www;
        index   index.html index.php;

        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location / {
            index index.html root2.html;
            methods GET;
            autoindex off;
        }
    }
}
