http {

    server {
        client_max_body_size -1;
        listen 127.0.0.1:8080;
        server_name webserv1.com localhost;
        
        root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
        
        error_page 400 /errors/400.html;
        error_page 403 /errors/403.html;
        error_page 404 /errors/404.html;
        error_page 405 /errors/405.html;
        error_page 413 /errors/413.html;
        error_page 500 /errors/500.html;

        location /bootstrap/ {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
            methods GET;
        }

        location / {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/clients/www1;
            index index.html;
            methods GET POST DELETE;
            autoindex off;

        }

        location /private {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
            methods GET POST DELETE;
        }

        location /test {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
            index index.html;
            methods POST GET DELETE;
            redirect http://www.google.com 301;
            autoindex on;
        }

        location /cgi_bin {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/clients/www1/cgi_bin;
            cgi_extension .php;
            cgi_path /usr/bin/php-cgi;
            methods GET POST DELETE;
        }

        location /uploads {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
            index index.html;
            methods GET POST DELETE;
            autoindex off;
        }
    }

}
