http {

    server {
        client_max_body_size 10000000;
        listen 127.0.0.1:8080;
        server_name webserv1.com localhost;
        
        root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
        
        error_page 400 /errors/400.html;
        error_page 403 /errors/403.html;
        error_page 404 /errors/404.html;
        error_page 405 /errors/405.html;
        error_page 408 /errors/408.html;
        error_page 413 /errors/413.html;
        error_page 500 /errors/500.html;
        error_page 505 /errors/505.html;

        location / {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/clients/www1;
            index index.html;
            methods GET POST DELETE;
            autoindex off;
        }
    }

    server {
        client_max_body_size 10000000;
        listen 127.0.0.1:8080;
        server_name webserv2.com;
        
        root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
        
        error_page 400 /errors/400.html;
        error_page 403 /errors/403.html;
        error_page 404 /errors/404.html;
        error_page 405 /errors/405.html;
        error_page 408 /errors/408.html;
        error_page 413 /errors/413.html;
        error_page 500 /errors/500.html;
        error_page 505 /errors/505.html;

        location / {
            root /home/rivoinfo/Pictures/Webserv/webservrivo/servers;
            index index.html;
            methods GET POST DELETE;
            autoindex off;
        }
    }

}
