http {

    server {
        client_max_body_size 2M;
        listen 127.0.0.1:8080;
        server_name www.webserv1.com test.com;
        
        root ./servers;
        index index.html;
        
        error_page 400 /errors/400.html;
        error_page 403 /errors/403.html;
        error_page 404 /errors/404.html;
        error_page 405 /errors/405.html;
        error_page 408 /errors/408.html;
        error_page 413 /errors/413.html;
        error_page 500 /errors/500.html;
        error_page 505 /errors/505.html;

        location /bootstrap/ {
            root ./servers;
            methods GET;
        }

        location / {
            root ./clients/www1;
            index index.html;
            methods GET POST DELETE;
            autoindex off;

        }

        location /private {
            root ./servers;
            methods GET POST DELETE;
            redirect http://www.google.com 303;
        }

        location /test {
            root ./servers;
            index index.html;
            methods POST GET DELETE;
            autoindex on;
        }

        location /cgi_bin {
            root ./clients/www1/cgi_bin;
            cgi_extension .php;
            cgi_path /usr/bin/php-cgi;
            methods GET POST DELETE;

        }

        location /uploads {
            root ./servers;
            index index.html;
            methods GET POST DELETE;
            autoindex off;
        }
    }

    server {
        client_max_body_size 10000000;
        listen 127.0.0.1:8081;
        server_name webserv2.com;

        root ./servers;
        
        location / {
            root ./clients/www2;
            index index.html;
            methods GET POST DELETE;
        }
    }

    server {
        client_max_body_size 10000000;
        listen 127.0.0.3:8082;
        server_name webserv3.com;
        
        root ./servers;
        
        location / {
            root ./clients/www3;
            index index1.html;
            methods GET POST DELETE;
        }
    }
}