
http {
	server
	{
		listen  127.0.0.1:8080;
		root www/;

		location / {
			index root.html;
			methods GET;
			autoindex off;
		}

		location /html {
			index index.html submit_data.html delete_data.html;
			methods GET POST DELETE;
			autoindex off;
		}

		location /static {
			index requestHanler.js style.css;
			methods GET;
			autoindex off;
		}

		location /test {
			methods GET;
			autoindex on;
		}

        location /cgi_bin {
			index form_handler.py GET_all.py delete_user.py;
			methods GET POST DELETE;
            cgi_extension .py;
            cgi_path /usr/bin/python3;
        }
	}
}
