http {

    server {
        client_max_body_size 50000;
        listen 127.0.0.1:8080;
        server_name webserv1.com localhost;
        
        root /home/safandri/Documents/Webserv/webservSafidy/www;
        
        error_page 400 /errors/400.html;
        error_page 403 /errors/403.html;

        location / {
            methods GET POST DELETE;
            autoindex off;
        }

    }

}
